version: "3.9"
services:
  msw:
    container_name: msw
    build: './msw'
    image: msw
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  login:
    container_name: login
    build: './login'
    image: login
    ports:
      - "3000:3000"
    depends_on:
      - msw